name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          python update_readme.py
          git commit -am "Update README" && git push
